services:
  db:
    image: mysql:8.0
    container_name: servesmart_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # ✅ Allows root without a password
      MYSQL_DATABASE: servesmart
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./servesmart.sql:/docker-entrypoint-initdb.d/servesmart.sql  

  redis:
    image: redis:latest
    container_name: servesmart_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: 2022bcd0038_servesmart_web
    container_name: servesmart_web
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8080:8081"
    environment:
      FLASK_ENV: development
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8081
      DATABASE_URL: mysql+mysqlconnector://root:@db/servesmart  # No password

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: 2022bcd0038_servesmart_worker
    container_name: servesmart_worker
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      FLASK_ENV: development
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: db+mysql://root:@db/servesmart  # No password

volumes:
  db_data:
