# Use an official Python runtime as a base image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy application files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run Celery worker
CMD ["celery", "-A", "tasks.celery", "worker", "--loglevel=info"]
